import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppInfoContext from "../contexts/AppInfoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Youtube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppInfoContext>{children}</AppInfoContext>
      </body>
    </html>
  );
}
